# Pytorch로 시작하는 딥러닝 입문

## 텐서 조작하기

In [1]:
import torch
import numpy as np

In [2]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6,])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [3]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [4]:
print(t[0], t[2:5], t[:])

tensor(0.) tensor([2., 3., 4.]) tensor([0., 1., 2., 3., 4., 5., 6.])


In [5]:
t = torch.FloatTensor([[1.,2.,3.], [4.,5.,6.,], [7.,8.,9.], [10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [6]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [7]:
print(t[:,1])
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [8]:
print(t[:,:-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [9]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('shape of matrix 1: ', m1.shape)
print('shape of matrix 2: ', m2.size())
print(m1.matmul(m2))

shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [10]:
print(m1*m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


matmul은 element-wise를 의미하고, *이나 mul은 그냥 행렬곱을 의미함

In [11]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [12]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t.mean())

tensor(2.5000)


In [13]:
print(t.mean(dim=0))

tensor([2., 3.])


In [14]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))


tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [15]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


docs에서는 argmax를 단순히 max를 통해서 구할 수 있다고 쓰여져 있는데 사실 걍 t.argmax를 사용해도 값은 나옴

In [16]:
t = np.array([[[0,1,2], [3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)

In [17]:
print(ft.shape)
print(ft)

torch.Size([2, 2, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [18]:
print(ft.view([-1,3]))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [19]:
print(ft.view([-1,1,3]))

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


In [20]:
ft

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

여전히 ft는 변함 없음을 확인함

In [21]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [22]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [23]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[[0.]],

        [[1.]],

        [[2.]]])
torch.Size([3, 1, 1])


사실상 unsqueeze안에 들어가는 값은 인덱스나 다름없음

view(), squeeze(), unsqueeze() 모두 텐서의 원소는 그대로 두고 텐서의 차원을 바꾸어 주는 함수들임

In [24]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [25]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [26]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [27]:
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [28]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [29]:
print(torch.cat([x,y]))
print(torch.cat([x,y]).shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])


default는 dim = 0일 때이니 유의해두기

In [30]:
print(torch.cat([x,y], dim = 1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [31]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [32]:
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [33]:
print(torch.cat([x,y,z]))

tensor([1., 4., 2., 5., 3., 6.])


단순 cat과 stack은 차이가 있음을 알아두자. cat은 tensor들을 병합하는 느낌이라면 stack은 단순히 쌓는 느낌

In [34]:
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [35]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [36]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [37]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [38]:
x = torch.FloatTensor([[1,2], [3,4]])

In [39]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [40]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## 파이썬 클래스

그냥 읽고 넘기기

## 선형회귀

In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [42]:
torch.manual_seed(1)

In [43]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=0.01)

epochs = 1999

for epoch in range(epochs + 1):
    
    hypothesis = x_train*W + b

    cost = torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:2d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, epochs + 1, W.item(), b.item(), cost.item()))

Epoch  0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch 100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch 200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch 300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch 400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch 500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch 600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch 700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch 800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch 900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008


In [44]:
w = torch.tensor(2.0, requires_grad=True)

z = 2*(w**2) + 5

z.backward()

print('z를 w로 미분한 값 : {}'.format(w.grad))

z를 w로 미분한 값 : 8.0


In [45]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [46]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [47]:
optimizer = optim.SGD([w1,w2,w3,b], lr = 1e-5)

np_epochs = 1000

for epoch in range(np_epochs + 1):
    
    hypothesis = w1*x1_train + w2*x2_train + w3*x3_train + b

    cost = torch.mean(((hypothesis - y_train)**2))

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0 :
        print('Epoch {}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(epoch, np_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()))

Epoch 0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch 100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch 200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch 300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch 400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch 500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch 600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch 700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch 800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch 900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079378


In [48]:
x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 80], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=1e-5)

total_epochs = 20

for epoch in range(total_epochs+1):
    
    hypothesis = x_train.matmul(W) + b

    cost = torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {}/{} hypothesis: {} Cost: {:.6f}'.format(epoch, total_epochs, hypothesis.squeeze().detach(), cost.item()))

Epoch 0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch 1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch 2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch 3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670898
Epoch 4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.482086
Epoch 5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch 6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch 7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch 8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch 9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch 10/20 hypothesis: tensor([153.5285, 184.4

detach()는 기본적으로 tensor를 복사하는 기능을 함. 위의 연습에서 알아둬야할 점은 기존 연산에서 추적되는 걸 방지하고 오로지 tensor 형태로만 뽑아온다는 것.  
이해가 안가면 detach()를 하고 안하고를 한번씩 돌려보면 알 듯

In [49]:
torch.manual_seed(1)

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

model = nn.Linear(1,1)

print(list(model.parameters()))

optimizer = optim.SGD(model.parameters(), lr = 0.01)

total_epochs = 2000

for epoch in range(total_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {}/{} Cost: {:.6f}'.format(epoch, total_epochs, cost.item()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Epoch 0/2000 Cost: 13.103541
Epoch 100/2000 Cost: 0.002791
Epoch 200/2000 Cost: 0.001724
Epoch 300/2000 Cost: 0.001066
Epoch 400/2000 Cost: 0.000658
Epoch 500/2000 Cost: 0.000407
Epoch 600/2000 Cost: 0.000251
Epoch 700/2000 Cost: 0.000155
Epoch 800/2000 Cost: 0.000096
Epoch 900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [50]:
new_data = torch.FloatTensor([[4.0]])

pred_y = model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[7.9989]], grad_fn=<AddmmBackward>)
[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


개인적으로 왜 [[4.0]]을 선언하는지는 잘 모르겠음. 실제로 [4.0]을 넣어서 돌려봐도 값은 동일하게 나온다. 굳이 차원을 늘리는 이유는 차원을 맞춰주기 위함인가?

In [51]:
torch.manual_seed(1)

x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 80], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = nn.Linear(3,1)

print(model.parameters())

optimizer = optim.SGD(model.parameters(),lr=1e-5)
total_epochs = 2000

for epoch in range(total_epochs+1):

    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0 :
        print('Epoch {}/{} Cost: {}'.format(epoch, total_epochs, cost.item()))

print(list(model.parameters()))

<generator object Module.parameters at 0x00000203850B9DD0>
Epoch 0/2000 Cost: 31584.34765625
Epoch 100/2000 Cost: 4.054811477661133
Epoch 200/2000 Cost: 3.8079185485839844
Epoch 300/2000 Cost: 3.5776000022888184
Epoch 400/2000 Cost: 3.3626468181610107
Epoch 500/2000 Cost: 3.1620583534240723
Epoch 600/2000 Cost: 2.9748358726501465
Epoch 700/2000 Cost: 2.8000454902648926
Epoch 800/2000 Cost: 2.6367905139923096
Epoch 900/2000 Cost: 2.484294891357422
Epoch 1000/2000 Cost: 2.3418288230895996
Epoch 1100/2000 Cost: 2.208688735961914
Epoch 1200/2000 Cost: 2.0842132568359375
Epoch 1300/2000 Cost: 1.9678411483764648
Epoch 1400/2000 Cost: 1.8590164184570312
Epoch 1500/2000 Cost: 1.75718092918396
Epoch 1600/2000 Cost: 1.6619274616241455
Epoch 1700/2000 Cost: 1.572750449180603
Epoch 1800/2000 Cost: 1.4892637729644775
Epoch 1900/2000 Cost: 1.4110760688781738
Epoch 2000/2000 Cost: 1.3378291130065918
[Parameter containing:
tensor([[1.0551, 0.5767, 0.3883]], requires_grad=True), Parameter containing:
t

In [52]:
class LinearRegression(nn.Module):
    def __init__(self):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [53]:
torch.manual_seed(1)

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

model = LinearRegression()
optimizer = optim.SGD(model.parameters(), lr = 0.01)
total_epochs = 2000

for epoch in range(total_epochs+1):
    
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {}/{} Cost: {:.6f}'.format(epoch, total_epochs, cost.item()))

Epoch 0/2000 Cost: 13.103541
Epoch 100/2000 Cost: 0.002791
Epoch 200/2000 Cost: 0.001724
Epoch 300/2000 Cost: 0.001066
Epoch 400/2000 Cost: 0.000658
Epoch 500/2000 Cost: 0.000407
Epoch 600/2000 Cost: 0.000251
Epoch 700/2000 Cost: 0.000155
Epoch 800/2000 Cost: 0.000096
Epoch 900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [54]:
class MultivariateLinearRegression(nn.Module):
    def __init__(self):
        super(MultivariateLinearRegression, self).__init__()
        self.linear = nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [55]:
torch.manual_seed(1)

x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 80], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = MultivariateLinearRegression()
optimizer = optim.SGD(model.parameters(), lr = 1e-5)
total_epochs = 2000

for epoch in range(total_epochs+1):

    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {}/{} Cost: {:.6f}'.format(epoch, total_epochs, cost.item()))

Epoch 0/2000 Cost: 31584.347656
Epoch 100/2000 Cost: 4.054811
Epoch 200/2000 Cost: 3.807919
Epoch 300/2000 Cost: 3.577600
Epoch 400/2000 Cost: 3.362647
Epoch 500/2000 Cost: 3.162058
Epoch 600/2000 Cost: 2.974836
Epoch 700/2000 Cost: 2.800045
Epoch 800/2000 Cost: 2.636791
Epoch 900/2000 Cost: 2.484295
Epoch 1000/2000 Cost: 2.341829
Epoch 1100/2000 Cost: 2.208689
Epoch 1200/2000 Cost: 2.084213
Epoch 1300/2000 Cost: 1.967841
Epoch 1400/2000 Cost: 1.859016
Epoch 1500/2000 Cost: 1.757181
Epoch 1600/2000 Cost: 1.661927
Epoch 1700/2000 Cost: 1.572750
Epoch 1800/2000 Cost: 1.489264
Epoch 1900/2000 Cost: 1.411076
Epoch 2000/2000 Cost: 1.337829


In [56]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0551, 0.5767, 0.3883]], requires_grad=True), Parameter containing:
tensor([0.2791], requires_grad=True)]


In [63]:
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 80], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, 2, shuffle=True)

model = MultivariateLinearRegression()
optimizer = optim.SGD(model.parameters(), lr = 1e-5)
total_epochs = 20

for epoch in range(total_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        #print(batch_idx)
        #print(samples)
        x_train, y_train = samples
        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {}/{} Batch {}/{} Cost: {:.6f}'.format(epoch, total_epochs, batch_idx+1, len(dataloader), cost.item()))
        

Epoch 0/20 Batch 1/3 Cost: 39813.523438
Epoch 0/20 Batch 2/3 Cost: 7718.927246
Epoch 0/20 Batch 3/3 Cost: 1913.156738
Epoch 1/20 Batch 1/3 Cost: 1263.947754
Epoch 1/20 Batch 2/3 Cost: 423.174194
Epoch 1/20 Batch 3/3 Cost: 171.226181
Epoch 2/20 Batch 1/3 Cost: 47.631317
Epoch 2/20 Batch 2/3 Cost: 11.627554
Epoch 2/20 Batch 3/3 Cost: 0.892520
Epoch 3/20 Batch 1/3 Cost: 4.801873
Epoch 3/20 Batch 2/3 Cost: 3.530174
Epoch 3/20 Batch 3/3 Cost: 4.487589
Epoch 4/20 Batch 1/3 Cost: 1.407378
Epoch 4/20 Batch 2/3 Cost: 4.184358
Epoch 4/20 Batch 3/3 Cost: 2.037946
Epoch 5/20 Batch 1/3 Cost: 1.664627
Epoch 5/20 Batch 2/3 Cost: 3.205698
Epoch 5/20 Batch 3/3 Cost: 2.843589
Epoch 6/20 Batch 1/3 Cost: 1.862180
Epoch 6/20 Batch 2/3 Cost: 1.189107
Epoch 6/20 Batch 3/3 Cost: 7.936528
Epoch 7/20 Batch 1/3 Cost: 1.893118
Epoch 7/20 Batch 2/3 Cost: 5.083883
Epoch 7/20 Batch 3/3 Cost: 1.962162
Epoch 8/20 Batch 1/3 Cost: 5.357918
Epoch 8/20 Batch 2/3 Cost: 2.842120
Epoch 8/20 Batch 3/3 Cost: 1.360269
Epoch 9/2

현재 위의 dataloader는 batch_idx와 sample로 이루어져 있음. 그리고 sample은 두개의 tensor로 x 데이터와 y 데이터로 구분되어 있음을 유의하자

## 커스텀 데이터셋으로 선형 회귀 구현하기

In [60]:
import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader
from torch.utils.data import Dataset

In [64]:
import torch
import torch.nn.functional as F
import torch.optim as optim
import torch.nn as nn

from torch.utils.data import DataLoader
from torch.utils.data import Dataset


class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75], [93, 88, 93], [89, 91, 80], [96, 98, 100], [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]

    def __len__(self):
        return len(self.x_data)

    def __getitem__(self, index):
        x = torch.tensor(self.x_data[index])
        y = torch.tensor(self.y_data[index])
        return x,y


dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
model = nn.Linear(3,1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)
total_epochs = 20

for epoch in range(total_epochs + 1):
    for batch_idx, sample in enumerate(dataloader):
        
        x_train, y_train = sample
        


In [65]:
len(x_train)

5