# Dropout과 Dead Relu는 어떤 차이점이 있을까?

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

import numpy as np
import copy

np.set_printoptions(threshold=np.inf, linewidth=np.inf)

In [27]:
relu_linear1 = nn.Linear(5, 5, bias=True)
relu_linear2 = nn.Linear(5, 5, bias=True)
relu_linear3 = nn.Linear(5, 2, bias=True)

relu_drop_linear1 = copy.deepcopy(relu_linear1)
relu_drop_linear2 = copy.deepcopy(relu_linear2)
relu_drop_linear3 = copy.deepcopy(relu_linear3)

drop_linear1 = copy.deepcopy(relu_linear1)
drop_linear2 = copy.deepcopy(relu_linear2)
drop_linear3 = copy.deepcopy(relu_linear3)

class Relu_model(nn.Module):
    def __init__(self):
        super(self, Relu_model).__init__()
        self.fc1 = relu_linear1
        self.fc2 = relu_linear2
        self.fc3 = relu_linear3
        self.relu = nn.ReLU()
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(x)
        out = self.relu(out)
        out = self.fc3(x)
        
        return out
        
class Relu_Dropout_model(nn.Module):
    def __init__(self):
        super(self, Relu_Dropout_model).__init__()
        self.fc1 = relu_drop_linear1
        self.fc2 = relu_drop_linear2
        self.fc3 = relu_drop_linear3
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.fc2(x)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.fc3(x)
        
        return out
    
class Dropout_model(nn.Module):
    def __init__(self):
        super(self, Dropout_model).__init__()
        self.fc1 = drop_linear1
        self.fc2 = drop_linear2
        self.fc3 = drop_linear3
        self.dropout = nn.Dropout(0.5)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.dropout(out)
        out = self.fc2(x)
        out = self.dropout(out)
        out = self.fc3(x)
        
        return out

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.Size([5, 5])


tensor([[ 0.6261,  0.5288,  0.2258, -0.3936,  1.7642],
        [ 0.6261,  0.5288,  0.2258, -0.3936,  1.7642],
        [ 0.6261,  0.5288,  0.2258, -0.3936,  1.7642],
        [ 0.6261,  0.5288,  0.2258, -0.3936,  1.7642],
        [ 0.6261,  0.5288,  0.2258, -0.3936,  1.7642]],
       grad_fn=<AddmmBackward>)


Parameter containing:
tensor([[ 0.3201, -0.0114,  0.3860, -0.4451,  0.3174],
        [ 0.1407,  0.3732, -0.0265, -0.3366,  0.4022],
        [ 0.2693, -0.1660, -0.1387, -0.0033, -0.1379],
        [-0.3087, -0.4380, -0.3057,  0.4064, -0.0942],
        [ 0.4112,  0.3114,  0.3191,  0.0384,  0.2642]], requires_grad=True)